import {
  Add01Icon,
  AddCircleIcon,
  Alert01Icon,
  AlertCircleIcon,
  AppleIcon,
  ArrowDown01Icon,
  ArrowDownRight01Icon,
  ArrowLeft01Icon,
  ArrowReloadHorizontalIcon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  ArrowUpDownIcon,
  ArrowUpRight01Icon,
  Attachment01Icon,
  BookOpen01Icon,
  Bookmark01Icon,
  Briefcase01Icon,
  Building01Icon,
  Calendar01Icon,
  Calendar03Icon,
  CalendarCheckIn01Icon,
  CalendarRemove01Icon,
  CallIcon,
  Camera01Icon,
  Cancel01Icon,
  CancelCircleIcon,
  CheckmarkBadge01Icon,
  CheckmarkCircle01Icon,
  CircleIcon,
  ClipboardIcon,
  Clock01Icon,
  CloudUploadIcon,
  CreditCardIcon,
  CurrencyIcon,
  DashboardSquare01Icon,
  Delete01Icon,
  Dollar01Icon,
  Download01Icon,
  EuroIcon,
  File01Icon,
  FileAddIcon,
  FileRemoveIcon,
  FileSearchIcon,
  FilterIcon,
  Folder01Icon,
  FolderAddIcon,
  FolderOpenIcon,
  GlobeIcon,
  GraduationScrollIcon,
  HeadsetIcon,
  Home01Icon,
  HourglassIcon,
  IdentityCardIcon,
  Image01Icon,
  InformationCircleIcon,
  JusticeScale01Icon,
  LayoutGridIcon,
  LayoutTwoRowIcon,
  LegalDocument01Icon,
  LeftToRightListBulletIcon,
  LinkSquare01Icon,
  Loading03Icon,
  Location01Icon,
  Logout01Icon,
  Mail01Icon,
  Megaphone01Icon,
  Message01Icon,
  Message02Icon,
  MessageMultiple01Icon,
  MinusSignIcon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  News01Icon,
  Notebook01Icon,
  Notification01Icon,
  PencilEdit01Icon,
  PlayIcon,
  Search01Icon,
  SecurityCheckIcon,
  SentIcon,
  Settings01Icon,
  SidebarLeftIcon,
  SparklesIcon,
  SquareLock01Icon,
  SquareUnlock01Icon,
  StarIcon,
  TableIcon,
  Tick01Icon,
  TickDouble01Icon,
  Timer01Icon,
  Upload01Icon,
  UserCircleIcon,
  UserIcon,
  Video01Icon,
  ViewIcon,
  ViewOffIcon,
} from '@hugeicons/core-free-icons'

export type AppIconData = typeof Add01Icon

export const appIcons = {
  arrowClockwise: ArrowReloadHorizontalIcon,
  arrowLeft: ArrowLeft01Icon,
  arrowRight: ArrowRight01Icon,
  arrowSquareOut: LinkSquare01Icon,
  arrowsClockwise: ArrowReloadHorizontalIcon,
  article: News01Icon,
  bell: Notification01Icon,
  bookOpen: BookOpen01Icon,
  bookmarkSimple: Bookmark01Icon,
  briefcase: Briefcase01Icon,
  buildings: Building01Icon,
  calendar: Calendar01Icon,
  calendarBlank: Calendar01Icon,
  calendarCheck: CalendarCheckIn01Icon,
  calendarDots: Calendar03Icon,
  calendarX: CalendarRemove01Icon,
  camera: Camera01Icon,
  caretDown: ArrowDown01Icon,
  caretLeft: ArrowLeft01Icon,
  caretRight: ArrowRight01Icon,
  caretUp: ArrowUp01Icon,
  caretUpDown: ArrowUpDownIcon,
  chatCircle: Message01Icon,
  chatCircleDots: Message02Icon,
  chatsCircle: MessageMultiple01Icon,
  check: Tick01Icon,
  checkCircle: CheckmarkCircle01Icon,
  checks: TickDouble01Icon,
  circle: CircleIcon,
  circleNotch: Loading03Icon,
  clipboard: ClipboardIcon,
  clipboardText: ClipboardIcon,
  clock: Clock01Icon,
  cloudArrowUp: CloudUploadIcon,
  creditCard: CreditCardIcon,
  currencyDollar: Dollar01Icon,
  currencyEur: EuroIcon,
  currencyNgn: CurrencyIcon,
  dashboardSquare: DashboardSquare01Icon,
  dotsThree: MoreHorizontalIcon,
  dotsThreeVertical: MoreVerticalIcon,
  downloadSimple: Download01Icon,
  envelope: Mail01Icon,
  envelopeSimple: Mail01Icon,
  eye: ViewIcon,
  eyeSlash: ViewOffIcon,
  faders: Settings01Icon,
  file: File01Icon,
  filePlus: FileAddIcon,
  fileSearch: FileSearchIcon,
  fileText: File01Icon,
  fileX: FileRemoveIcon,
  folder: Folder01Icon,
  folderOpen: FolderOpenIcon,
  folderPlus: FolderAddIcon,
  funnel: FilterIcon,
  gearSix: Settings01Icon,
  globeHemisphereWest: GlobeIcon,
  graduationCap: GraduationScrollIcon,
  headset: HeadsetIcon,
  hourglass: HourglassIcon,
  house: Home01Icon,
  identificationCard: IdentityCardIcon,
  image: Image01Icon,
  info: InformationCircleIcon,
  legalDocument: LegalDocument01Icon,
  listBullets: LeftToRightListBulletIcon,
  lock: SquareLock01Icon,
  lockSimple: SquareLock01Icon,
  lockSimpleOpen: SquareUnlock01Icon,
  magnifyingGlass: Search01Icon,
  mapPin: Location01Icon,
  megaphoneSimple: Megaphone01Icon,
  minus: MinusSignIcon,
  notebook: Notebook01Icon,
  paperPlaneRight: SentIcon,
  paperclip: Attachment01Icon,
  pencilSimple: PencilEdit01Icon,
  pencilSimpleLine: PencilEdit01Icon,
  phone: CallIcon,
  play: PlayIcon,
  plus: Add01Icon,
  plusCircle: AddCircleIcon,
  rows: LayoutTwoRowIcon,
  scales: JusticeScale01Icon,
  sealCheck: CheckmarkBadge01Icon,
  shieldCheck: SecurityCheckIcon,
  sidebarSimple: SidebarLeftIcon,
  signOut: Logout01Icon,
  sparkle: SparklesIcon,
  spinnerGap: Loading03Icon,
  squaresFour: LayoutGridIcon,
  star: StarIcon,
  table: TableIcon,
  timer: Timer01Icon,
  trash: Delete01Icon,
  trayArrowDown: Download01Icon,
  trendDown: ArrowDownRight01Icon,
  trendUp: ArrowUpRight01Icon,
  uploadSimple: Upload01Icon,
  user: UserIcon,
  userCircle: UserCircleIcon,
  videoCamera: Video01Icon,
  warning: Alert01Icon,
  warningCircle: AlertCircleIcon,
  x: Cancel01Icon,
  xCircle: CancelCircleIcon,
  apple: AppleIcon,
} as const satisfies Record<string, AppIconData>

export type AppIconName = keyof typeof appIcons

export function appIcon(name: AppIconName): AppIconData {
  return appIcons[name]
}

const TOKEN_ICON_MAP: Array<[string, AppIconName]> = [
  ['eye-off', 'eyeSlash'],
  ['eye_off', 'eyeSlash'],
  ['eye', 'eye'],
  ['loading', 'circleNotch'],
  ['arrow-path', 'circleNotch'],
  ['alert-circle', 'warningCircle'],
  ['alert_circle', 'warningCircle'],
  ['calendar-remove', 'calendarX'],
  ['calendar_remove', 'calendarX'],
  ['check-badge', 'sealCheck'],
  ['check_badge', 'sealCheck'],
  ['shield-check', 'shieldCheck'],
  ['shield_check', 'shieldCheck'],
  ['x-circle', 'xCircle'],
  ['x_circle', 'xCircle'],
  ['check-circle', 'checkCircle'],
  ['check_circle', 'checkCircle'],
  ['check', 'check'],
  ['information-circle', 'info'],
  ['information_circle', 'info'],
  ['chevron-down', 'caretDown'],
  ['chevron_down', 'caretDown'],
  ['chevron-right', 'caretRight'],
  ['chevron_right', 'caretRight'],
  ['video-camera', 'videoCamera'],
  ['video_camera', 'videoCamera'],
  ['phone', 'phone'],
  ['clock', 'clock'],
  ['notebook', 'notebook'],
  ['money', 'currencyDollar'],
  ['cancel', 'x'],
  ['file-not-found', 'fileX'],
  ['file_not_found', 'fileX'],
  ['apple', 'apple'],
  ['envelope', 'envelope'],
  ['info', 'info'],
  ['user-circle', 'userCircle'],
  ['user_circle', 'userCircle'],
  ['user', 'user'],
  ['map-pin', 'mapPin'],
  ['map_pin', 'mapPin'],
  ['briefcase', 'briefcase'],
  ['identification', 'identificationCard'],
  ['document-text', 'fileText'],
  ['document_text', 'fileText'],
  ['document', 'file'],
  ['photo', 'image'],
  ['image', 'image'],
  ['arrow-down-tray', 'trayArrowDown'],
  ['arrow_down_tray', 'trayArrowDown'],
  ['folder-plus', 'folderPlus'],
  ['folder_plus', 'folderPlus'],
  ['folder', 'folder'],
  ['cloud-arrow-up', 'cloudArrowUp'],
  ['cloud_arrow_up', 'cloudArrowUp'],
  ['ellipsis-vertical', 'dotsThreeVertical'],
  ['calendar-days', 'calendarDots'],
  ['calendar_days', 'calendarDots'],
  ['calendar', 'calendarBlank'],
  ['exclamation-triangle', 'warning'],
  ['exclamation_triangle', 'warning'],
  ['chat-bubble-left-ellipsis', 'chatsCircle'],
  ['chat_bubble_left_ellipsis', 'chatsCircle'],
  ['chat-bubble', 'chatCircle'],
  ['chat_bubble', 'chatCircle'],
  ['play', 'play'],
  ['banknotes', 'currencyDollar'],
  ['banknote', 'currencyDollar'],
  ['building-library', 'bookOpen'],
  ['building_library', 'bookOpen'],
  ['building-office', 'buildings'],
  ['building_office', 'buildings'],
  ['scale', 'scales'],
  ['academic-cap', 'graduationCap'],
  ['academic_cap', 'graduationCap'],
  ['paper-clip', 'paperclip'],
  ['paper_clip', 'paperclip'],
  ['table-cells', 'table'],
  ['table_cells', 'table'],
  ['trash', 'trash'],
  ['eye-slash', 'eyeSlash'],
  ['eye_slash', 'eyeSlash'],
  ['x-mark', 'x'],
  ['x_mark', 'x'],
  ['squares-2x2', 'squaresFour'],
  ['squares_2x2', 'squaresFour'],
  ['list-bullet', 'listBullets'],
  ['list_bullet', 'listBullets'],
  ['funnel', 'funnel'],
  ['bookmark', 'bookmarkSimple'],
  ['magnifying-glass', 'magnifyingGlass'],
  ['magnifying_glass', 'magnifyingGlass'],
  ['house', 'house'],
  ['home', 'house'],
  ['rows', 'rows'],
]

export function normalizeIconToken(raw: string): string {
  return raw
    .trim()
    .toLowerCase()
    .replace(/^i-(heroicons|hugeicons|lucide)-/, '')
    .replace(/^heroicons:/, '')
    .replace(/^ph:/, '')
}

export function resolveAppIconName(raw: string): AppIconName {
  const token = normalizeIconToken(raw)
  if (!token)
    return 'dotsThree'

  for (const [needle, iconName] of TOKEN_ICON_MAP) {
    if (token.includes(needle))
      return iconName
  }

  return 'dotsThree'
}

export function resolveAppIcon(raw: string): AppIconData {
  return appIcons[resolveAppIconName(raw)]
}
