/**
 * Integration Test: URL Shareability
 * Feature: public-pages-phase-1
 * 
 * Tests that URLs generated by the application are valid, shareable,
 * and can be bookmarked. This test simulates real-world scenarios
 * where users share or bookmark URLs.
 * 
 * Validates: Requirements 8.3
 */

import { describe, it, expect } from 'vitest'
import { filtersToQuery, filtersFromQuery } from '~/composables/useLawyerFilters'
import type { FilterState } from '~/types/filter'

describe('URL Shareability Integration Tests', () => {
  it('should generate shareable URL for basic search', () => {
    const filters: FilterState = {
      practiceAreas: ['family-law'],
      location: 'New York',
      consultationTypes: ['video'],
      minRating: null,
      minExperience: null,
      priceRange: { min: null, max: null },
      keywords: '',
      lawyerName: '',
      certifications: [],
      languages: []
    }
    
    // Generate URL
    const query = filtersToQuery(filters)
    const searchParams = new URLSearchParams()
    for (const [key, value] of Object.entries(query)) {
      if (value !== undefined && value !== null) {
        searchParams.append(key, String(value))
      }
    }
    
    const url = `https://example.com/lawyers?${searchParams.toString()}`
    
    // Verify URL is valid
    expect(() => new URL(url)).not.toThrow()
    
    // Simulate sharing: another user receives this URL
    const receivedUrl = new URL(url)
    const receivedQuery = Object.fromEntries(receivedUrl.searchParams.entries())
    
    // Reconstruct filters from received URL
    const reconstructedFilters = filtersFromQuery(receivedQuery)
    
    // Verify filters match original
    expect(reconstructedFilters.practiceAreas).toEqual(filters.practiceAreas)
    expect(reconstructedFilters.location).toBe(filters.location)
    expect(reconstructedFilters.consultationTypes).toEqual(filters.consultationTypes)
  })

  it('should generate shareable URL with all filters applied', () => {
    const filters: FilterState = {
      practiceAreas: ['family-law', 'criminal-defense'],
      location: 'Los Angeles',
      consultationTypes: ['video', 'phone'],
      minRating: 4,
      minExperience: 10,
      priceRange: { min: 100, max: 500 },
      keywords: 'divorce',
      lawyerName: 'Smith',
      certifications: ['bar-certified'],
      languages: ['English', 'Spanish']
    }
    
    // Generate URL
    const query = filtersToQuery(filters)
    const searchParams = new URLSearchParams()
    for (const [key, value] of Object.entries(query)) {
      if (value !== undefined && value !== null) {
        searchParams.append(key, String(value))
      }
    }
    
    const url = `https://example.com/lawyers?${searchParams.toString()}`
    
    // Verify URL is valid
    const parsedUrl = new URL(url)
    expect(parsedUrl.protocol).toBe('https:')
    expect(parsedUrl.pathname).toBe('/lawyers')
    
    // Simulate bookmarking: save and restore URL
    const bookmarkedUrl = url
    const restoredUrl = new URL(bookmarkedUrl)
    const restoredQuery = Object.fromEntries(restoredUrl.searchParams.entries())
    
    // Reconstruct filters from bookmarked URL
    const reconstructedFilters = filtersFromQuery(restoredQuery)
    
    // Verify all filters are preserved
    expect(reconstructedFilters.practiceAreas).toEqual(filters.practiceAreas)
    expect(reconstructedFilters.location).toBe(filters.location)
    expect(reconstructedFilters.consultationTypes).toEqual(filters.consultationTypes)
    expect(reconstructedFilters.minRating).toBe(filters.minRating)
    expect(reconstructedFilters.minExperience).toBe(filters.minExperience)
    expect(reconstructedFilters.priceRange.min).toBe(filters.priceRange.min)
    expect(reconstructedFilters.priceRange.max).toBe(filters.priceRange.max)
    expect(reconstructedFilters.keywords).toBe(filters.keywords)
    expect(reconstructedFilters.lawyerName).toBe(filters.lawyerName)
    expect(reconstructedFilters.certifications).toEqual(filters.certifications)
    expect(reconstructedFilters.languages).toEqual(filters.languages)
  })

  it('should handle special characters in location and keywords', () => {
    const filters: FilterState = {
      practiceAreas: ['family-law'],
      location: 'San José, CA',
      consultationTypes: ['video'],
      minRating: null,
      minExperience: null,
      priceRange: { min: null, max: null },
      keywords: 'child custody & support',
      lawyerName: '',
      certifications: [],
      languages: []
    }
    
    // Generate URL
    const query = filtersToQuery(filters)
    const searchParams = new URLSearchParams()
    for (const [key, value] of Object.entries(query)) {
      if (value !== undefined && value !== null) {
        searchParams.append(key, String(value))
      }
    }
    
    const url = `https://example.com/lawyers?${searchParams.toString()}`
    
    // Verify URL is valid (special characters should be encoded)
    expect(() => new URL(url)).not.toThrow()
    
    // Verify special characters are properly encoded (URLSearchParams uses + for spaces, which is valid)
    expect(url).toMatch(/Jos%C3%A9/) // José should be encoded
    expect(url).toMatch(/custody.*support/) // Keywords should be present
    expect(url).toMatch(/%26/) // & should be encoded
    
    // Simulate sharing and decoding
    const receivedUrl = new URL(url)
    const receivedQuery = Object.fromEntries(receivedUrl.searchParams.entries())
    const reconstructedFilters = filtersFromQuery(receivedQuery)
    
    // Verify special characters are preserved after decoding
    expect(reconstructedFilters.location).toBe(filters.location)
    expect(reconstructedFilters.keywords).toBe(filters.keywords)
  })

  it('should generate bookmarkable URL with no filters (default state)', () => {
    const filters: FilterState = {
      practiceAreas: [],
      location: '',
      consultationTypes: [],
      minRating: null,
      minExperience: null,
      priceRange: { min: null, max: null },
      keywords: '',
      lawyerName: '',
      certifications: [],
      languages: []
    }
    
    // Generate URL
    const query = filtersToQuery(filters)
    const searchParams = new URLSearchParams()
    for (const [key, value] of Object.entries(query)) {
      if (value !== undefined && value !== null) {
        searchParams.append(key, String(value))
      }
    }
    
    const queryString = searchParams.toString()
    const url = queryString ? `https://example.com/lawyers?${queryString}` : 'https://example.com/lawyers'
    
    // Verify URL is valid (should be just the base URL)
    const parsedUrl = new URL(url)
    expect(parsedUrl.pathname).toBe('/lawyers')
    expect(parsedUrl.search).toBe('')
  })

  it('should maintain URL validity across multiple round-trips', () => {
    const originalFilters: FilterState = {
      practiceAreas: ['corporate-law', 'tax-law'],
      location: 'Chicago',
      consultationTypes: ['in-person'],
      minRating: 5,
      minExperience: 15,
      priceRange: { min: 200, max: 800 },
      keywords: 'mergers',
      lawyerName: '',
      certifications: ['tax-specialist'],
      languages: ['English']
    }
    
    // First round-trip
    const query1 = filtersToQuery(originalFilters)
    const filters1 = filtersFromQuery(query1)
    
    // Second round-trip
    const query2 = filtersToQuery(filters1)
    const filters2 = filtersFromQuery(query2)
    
    // Third round-trip
    const query3 = filtersToQuery(filters2)
    const filters3 = filtersFromQuery(query3)
    
    // All should be identical
    expect(filters1).toEqual(originalFilters)
    expect(filters2).toEqual(originalFilters)
    expect(filters3).toEqual(originalFilters)
    expect(query1).toEqual(query2)
    expect(query2).toEqual(query3)
  })

  it('should generate URLs under 2000 characters for practical use', () => {
    // Create a filter state with maximum realistic values
    const filters: FilterState = {
      practiceAreas: ['family-law', 'criminal-defense', 'corporate-law', 'real-estate-law', 'immigration-law'],
      location: 'San Francisco Bay Area, California',
      consultationTypes: ['video', 'phone', 'in-person'],
      minRating: 4,
      minExperience: 10,
      priceRange: { min: 100, max: 1000 },
      keywords: 'experienced attorney with trial experience',
      lawyerName: 'Johnson',
      certifications: ['bar-certified', 'board-certified', 'specialist'],
      languages: ['English', 'Spanish', 'French']
    }
    
    // Generate URL
    const query = filtersToQuery(filters)
    const searchParams = new URLSearchParams()
    for (const [key, value] of Object.entries(query)) {
      if (value !== undefined && value !== null) {
        searchParams.append(key, String(value))
      }
    }
    
    const url = `https://example.com/lawyers?${searchParams.toString()}`
    
    // Verify URL length is reasonable (under 2000 characters)
    // This ensures URLs work in all browsers and can be easily shared
    expect(url.length).toBeLessThan(2000)
  })
})
